### ISSUE TITLE
error in new and existing projects

### ISSUE THREAD

**Issue by QuantumBitsIT** [GoogleCloudPlatform/data-analytics-golden-demo#122]
I have followed all the steps as described, when deploying to an existing projects I get this error messages when I say yes to terraform deploy:

│ Error: failed pre-requisites: failed to check permissions on billing account "billingAccounts/0145B6-A413DD-11DC2D": Post "https://cloudbilling.googleapis.com/v1/billingAccounts/0145B6-A413DD-11DC2D:testIamPermissions?alt=json&prettyPrint=false": oauth2/google: invalid token JSON from metadata: EOF
│ 
│   with module.project[0].google_project.project,
│   on ../terraform-modules/project/tf-project.tf line 45, in resource "google_project" "project":
│   45: resource "google_project" "project" {

 I tried running at the org level with the admin user and I get the following error after typing yes to terraform deploy:

╷
│ Error: failed pre-requisites: failed to check permissions on billing account "billingAccounts/0145B6-A413DD-11DC2D": Post "https://cloudbilling.googleapis.com/v1/billingAccounts/0145B6-A413DD-11DC2D:testIamPermissions?alt=json&prettyPrint=false": oauth2/google: invalid token JSON from metadata: EOF
│ 
│   with module.project[0].google_project.project,
│   on ../terraform-modules/project/tf-project.tf line 45, in resource "google_project" "project":
│   45: resource "google_project" "project" {

**Comment by AdamPaternostro** [comment]
Can you try adding roles/billing.user to your user?  I think I have that be default.  If that works, I can update the documentation.  Thx.

**Comment by QuantumBitsIT** [comment]
I tired again with more roles but I still get the same error message. Can we set up a quick session to look at my environment? I can set up a zoom call any time next few days.
