### ISSUE TITLE
Update `template_file` module to  `

### ISSUE THREAD

**Issue by dinigo** [GoogleCloudPlatform/data-analytics-golden-demo#46]
The `template_file` module was [deprecated](https://registry.terraform.io/providers/hashicorp/template/latest/docs#deprecation) as of last year. As a consequence, when Mac M1 laptops where shipped this module was never built for arm64. 

The project simply wont run for M1 Macs in the last Terraform versions.

To fix it Terraform suggest to r[eplace it with the function `templatefile()`](https://developer.hashicorp.com/terraform/language/functions/templatefile)

**Comment by AdamPaternostro** [comment]
Yes, this should be fixed soon.

**Comment by AdamPaternostro** [comment]
This has been corrected: https://github.com/GoogleCloudPlatform/data-analytics-golden-demo/blob/main/terraform-modules/sql-scripts/tf-sql-scripts.tf
