### ISSUE TITLE
Hardcoded region and location

### ISSUE THREAD

**Issue by dinigo** [GoogleCloudPlatform/data-analytics-golden-demo#47]
Location and region is hardcoded over and over in the terraform config.

This makes it difficult to extract the location/region to be abale to easily localise the deployment

Location/Region MUST be configurable from the outside

**Comment by AdamPaternostro** [comment]
Some of this is due to preview features and only being in certain regions.  I will have a preview region for these services.

**Comment by AdamPaternostro** [comment]
This has been corrected: https://github.com/GoogleCloudPlatform/data-analytics-golden-demo/blob/main/terraform/tf-variables.tf#L103-L266

**Comment by AdamPaternostro** [comment]
Please see this for an EU deployment (this has been tested) https://github.com/GoogleCloudPlatform/data-analytics-golden-demo/blob/main/deploy-europe-region.sh
