### ISSUE TITLE
Incorrect variable used

### ISSUE THREAD

**Issue by vinsonrogers** [GoogleCloudPlatform/data-analytics-golden-demo#5]
https://github.com/GoogleCloudPlatform/data-analytics-golden-demo/blob/bfc1acca898f27cf16984bd3ecb73aa3e106e3b8/deploy.sh#L70

This looks like it should be `org_id` instead of `billing_account`

**Comment by AdamPaternostro** [comment]
Thanks.  The code has been updated.
