### ISSUE TITLE
ERROR: WITH CONNECTION clause is unsupported for CREATE TABLE at Bigquery

### ISSUE THREAD

**Issue by ericksc** [GoogleCloudPlatform/data-analytics-golden-demo#90]
At Bigquery:
When I tried to run the create managed table Bigquery SQL code I got an error shown in the screenshot

https://github.com/GoogleCloudPlatform/data-analytics-golden-demo/blob/178c002367510688c46c0f6b07dbdbb9f8fd5e79/sql-scripts/taxi_dataset/sp_demo_biglake_managed_tables.sql#L66C1-L75C109

![image](https://github.com/GoogleCloudPlatform/data-analytics-golden-demo/assets/20059518/0f7e5008-12d6-4e34-a747-0e3fbd613998)

**Comment by velascoluis** [comment]
Hi, as of today, BigLake Managed Tables feature is on private preview, you will need your project to be allow-listed in order to use it.
You can have a look at this video if you want to see it in action : https://www.youtube.com/watch?v=D4BhIraXP-I

**Comment by ericksc** [comment]
@velascoluis Thank you so much for your answer. how can my project be added into allow-listed?
